validates:
  user:
    maximum_name: 50
    maximum_email: 255
    minimum_pass: 6
  location_type:
    maximum_name: 50
  service:
    maximum_name: 50
  bed_detail:
    maximum_name: 50

models:
  user:
    waiting_time: 2

search_fields:
  user: ["name", "email", "created_at", "updated_at"]
  location_type: ["name", "created_at", "updated_at"]
  room: ["name", "occupancy_limit", "living_room", "bed_room", "bath_room",
    "number_of_bed", "quantity", "price", "created_at", "updated_at"]
  location: ["name", "national", "zip_code", "description", "status",
    "location_type_id", "user_id", "created_at", "updated_at"]
  service: ["name", "created_at", "updated_at"]
  bed_detail: ["name", "created_at", "updated_at"]
  reservation: ["total_bill", "created_at", "updated_at"]
  location_home: ["name", "national", "location"]

controllers:
  admin:
    users:
      pag: 10
    location_types:
      pag: 10
    services:
      pag: 10
    bed_details:
      pag: 10
    locations:
      page: 5
  manager:
    rooms:
      page: 5
    locations:
      page: 5
    reservations:
      page: 10
      status: 2
  locations:
    pag: 9
  static_pages:
    page: 9
    limit_location: 6

manager:
  rooms:
    index:
      page: 5

reviews:
  form:
    row_numbers: 3

rooms:
  shows:
    minimum_room: 1

static_pages:
  location:
    number_of_pictures: 0
  search_home:
    occupancy_limit: [["1",1], ["2",2], ["3",3], ["4",4], ["5",5], ["6",6], ["7+",7]]
    living_room: [["1",1], ["2",2], ["3",3], ["4+",4]]
    bed_room: [["1",1], ["2",2], ["3",3], ["4+",4]]
    bath_room: [["1",1], ["2",2], ["3",3], ["4+",4]]
    total_rate: [["1",1], ["2",2], ["3",3], ["4",4], ["5",5]]
